"""empty message

Revision ID: 902910024597
Revises: 1040232346c3
Create Date: 2024-08-21 22:31:02.727086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902910024597'
down_revision = '1040232346c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opd_list')
    with op.batch_alter_table('patient_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_records', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_details', schema=None) as batch_op:
        batch_op.drop_column('can_view_records')

    op.create_table('opd_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('can_view_records', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
